{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1c8b49f9-470d-4390-9742-d7c6dae9de31",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{\n",
      "  \"url\": \"-f\",\n",
      "  \"error\": \"Invalid URL '-f': No scheme supplied. Perhaps you meant https://-f?\",\n",
      "  \"https\": false,\n",
      "  \"redirect_to_https\": false,\n",
      "  \"security_headers\": {},\n",
      "  \"cookies_secure\": [],\n",
      "  \"cookies_httponly\": []\n",
      "}\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "import sys\n",
    "import json\n",
    "\n",
    "def scan_website(url):\n",
    "    \"\"\"\n",
    "    Scans a website for basic security configurations.\n",
    "    Returns a dictionary with check results.\n",
    "    \"\"\"\n",
    "    results = {\n",
    "        \"url\": https://www.google.com,\n",
    "        \"error\": None,\n",
    "        \"https\": False,\n",
    "        \"redirect_to_https\": False,\n",
    "        \"security_headers\": {},\n",
    "        \"cookies_secure\": [],\n",
    "        \"cookies_httponly\": []\n",
    "    }\n",
    "\n",
    "    try:\n",
    "        # Force HTTPS if user gave http\n",
    "        if url.startswith(\"http://\"):\n",
    "            url = url.replace(\"http://\", \"https://\", 1)\n",
    "\n",
    "        # Send request with redirect following\n",
    "        response = requests.get(\n",
    "            url,\n",
    "            allow_redirects=True,\n",
    "            timeout=10,\n",
    "            verify=True  # checks SSL certificate\n",
    "        )\n",
    "\n",
    "        # 1. HTTPS usage\n",
    "        results[\"https\"] = response.url.startswith(\"https://\")\n",
    "\n",
    "        # 2. HTTP → HTTPS redirection (if original was http and final is https)\n",
    "        if url.startswith(\"http://\"):\n",
    "            # We already changed it, but check history\n",
    "            results[\"redirect_to_https\"] = len(response.history) > 0 and any(\n",
    "                r.status_code in (301, 302) for r in response.history\n",
    "            )\n",
    "        else:\n",
    "            results[\"redirect_to_https\"] = True  # already https\n",
    "\n",
    "        # 3. Important security headers\n",
    "        important_headers = [\n",
    "            \"Strict-Transport-Security\",\n",
    "            \"Content-Security-Policy\",\n",
    "            \"X-Frame-Options\",\n",
    "            \"X-Content-Type-Options\",\n",
    "            \"Referrer-Policy\",\n",
    "            \"Permissions-Policy\"  # sometimes called Feature-Policy\n",
    "        ]\n",
    "\n",
    "        headers_lower = {k.lower(): v for k, v in response.headers.items()}\n",
    "        for header in important_headers:\n",
    "            lower_key = header.lower()\n",
    "            results[\"security_headers\"][header] = lower_key in headers_lower\n",
    "\n",
    "        # 4. Cookie flags (Secure & HttpOnly)\n",
    "        for cookie in response.cookies:\n",
    "            name = cookie.name\n",
    "            if cookie.secure:\n",
    "                results[\"cookies_secure\"].append(name)\n",
    "            if cookie.get_nonstandard_attr(\"HttpOnly\") or \"httponly\" in cookie._rest:\n",
    "                results[\"cookies_httponly\"].append(name)\n",
    "\n",
    "        # Final status code for info\n",
    "        results[\"status_code\"] = response.status_code\n",
    "\n",
    "    except requests.exceptions.RequestException as e:\n",
    "        results[\"error\"] = str(e)\n",
    "\n",
    "    return results\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    if len(sys.argv) < 2:\n",
    "        print(\"Usage: python scan.py <url>\")\n",
    "        print(\"Example: python scan.py https://example.com\")\n",
    "        sys.exit(1)\n",
    "\n",
    "    url = sys.argv[1]\n",
    "    scan_result = scan_website(url)\n",
    "\n",
    "    # Print nicely formatted JSON\n",
    "    print(json.dumps(scan_result, indent=2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2074073c-c841-45a2-8c2c-98996003d4ac",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
